#!/bin/bash
set -e

# ==========================================
# Multi-Environment Deployment Script (Refactored & Secure)
# ==========================================

# Load environment variables generated by .gitlab-ci.yml
if [ -f deploy.env ]; then
    source deploy.env
fi

# ==========================================
# Configuration & Dynamic Naming
# ==========================================

ENV_BASE_DIR="/opt/environments"
PORT_RANGE_START=3501
PORT_RANGE_END=3550
CLOUDFLARED_TUNNEL_IMAGE="cloudflare/cloudflared:latest"
PROJECT_NAME="${CI_PROJECT_NAME}" 
IMAGE_TAG="${CI_COMMIT_SHORT_SHA:-latest}"
ROOT_DOMAIN="iimlab.id"

# 1. Tentukan Environment Type & Ambil Tunnel ID dari Variable GitLab
case "$DEPLOY_ENV" in
    dev)
        TUNNEL_ID="${DEV_TUNNEL_ID}"
        TUNNEL_SERVICE_NAME="dev_tunnel"
        ;;
    stage)
        TUNNEL_ID="${STAGE_TUNNEL_ID}"
        TUNNEL_SERVICE_NAME="stage_tunnel"
        ;;
    prod)
        TUNNEL_ID="${PROD_TUNNEL_ID}"
        TUNNEL_SERVICE_NAME="prod_tunnel"
        ;;
    *)
        echo "❌ Unknown environment: $DEPLOY_ENV" >&2
        exit 1
        ;;
esac

# Cek Safety: Pastikan Tunnel ID ada
if [ -z "$TUNNEL_ID" ]; then
    echo "❌ Error: TUNNEL_ID is empty! Please check GitLab CI/CD Variables." >&2
    exit 1
fi

# 2. Logika Penamaan Subdomain & Container
CLEAN_BRANCH=$(echo "$CI_COMMIT_BRANCH" | tr '[:upper:]' '[:lower:]')

if [ "$DEPLOY_ENV" == "prod" ]; then
    SUBDOMAIN="${PROD_SUBDOMAIN_OVERRIDE:-$PROJECT_NAME}"
    CONTAINER_NAME="prod_${PROJECT_NAME}"
elif [ "$DEPLOY_ENV" == "stage" ]; then
    SUBDOMAIN="stage_${PROJECT_NAME}"
    CONTAINER_NAME="stage_${PROJECT_NAME}"
else
    SUBDOMAIN="${CLEAN_BRANCH}_${PROJECT_NAME}"
    CONTAINER_NAME="${CLEAN_BRANCH}_${PROJECT_NAME}"
fi

FULL_HOSTNAME="${SUBDOMAIN}.${ROOT_DOMAIN}"
IMAGE_NAME="${PROJECT_NAME}:${IMAGE_TAG}"

# Environment paths
ENV_DIR="${ENV_BASE_DIR}/${DEPLOY_ENV}"
CONFIG_DIR="${ENV_DIR}/configs" 
mkdir -p "${CONFIG_DIR}"

CLOUDFLARED_DIR="${ENV_DIR}/cloudflared"
DOCKER_COMPOSE_FILE="${ENV_DIR}/docker-compose.yml"
CLOUDFLARED_CONFIG="${CLOUDFLARED_DIR}/config.yml"

# ==========================================
# Helper Functions
# ==========================================
log_info() { echo -e "\n✅ [INFO] $1" >&2; }
log_warn() { echo -e "\n⚠️  [WARN] $1" >&2; }
log_error() { echo -e "\n❌ [ERROR] $1" >&2; }

# ==========================================
# Port Management Logic (Stateless)
# ==========================================

get_assigned_port() {
    local existing_port=""
    
    if [ -f "$DOCKER_COMPOSE_FILE" ]; then
        # Coba ambil port dari konfigurasi yang sudah ada
        existing_port=$(grep -A 10 "container_name: ${CONTAINER_NAME}$" "$DOCKER_COMPOSE_FILE" | grep -m 1 -oP ' - "\K[0-9]+(?=:)')
    fi

    if [ ! -z "$existing_port" ]; then
        echo "$existing_port"
        return 0
    fi

    # Jika tidak ketemu, cari port baru
    local used_ports=""
    if [ -f "$DOCKER_COMPOSE_FILE" ]; then
        used_ports=$(grep -oP ' - "\K[0-9]+(?=:)' "$DOCKER_COMPOSE_FILE" | sort -u)
    fi

    for port in $(seq $PORT_RANGE_START $PORT_RANGE_END); do
        if echo "$used_ports" | grep -q "^${port}$"; then continue; fi
        if ss -tuln 2>/dev/null | grep -q ":${port} "; then continue; fi
        echo "$port"
        return 0
    done

    log_error "No available ports in range $PORT_RANGE_START-$PORT_RANGE_END"
    exit 1
}

# ==========================================
# Rewrite Logic Functions
# ==========================================

update_cloudflare_config() {
    local container_target=$1
    local internal_port=$2
    
    log_info "Updating Cloudflare Config for: $FULL_HOSTNAME"
    
    if [ ! -f "${CLOUDFLARED_CONFIG}" ]; then
        log_error "Cloudflare config not found at ${CLOUDFLARED_CONFIG}"
        exit 1
    fi

    # 1. Hapus Entry Lama 
    sed -i "/hostname: ${FULL_HOSTNAME}/,+1d" ${CLOUDFLARED_CONFIG}

    # 2. Generate Entry Baru (Insert sebelum catch-all rule)
    local new_entry="  - hostname: ${FULL_HOSTNAME}\n    service: http://${container_target}:${internal_port}"
    
    awk -v entry="$new_entry" '
        /service: http_status:404/ {
            print entry
            print $0
            next
        }
        {print}
    ' ${CLOUDFLARED_CONFIG} > ${CLOUDFLARED_CONFIG}.tmp && mv ${CLOUDFLARED_CONFIG}.tmp ${CLOUDFLARED_CONFIG}
}

update_docker_compose() {
    local port=$1
    local internal_port=${2:-3140}
    
    log_info "Updating Docker Compose for: $CONTAINER_NAME on port $port"

    # Export block service ke environment variable
    # NOTE: Format ini otomatis membuat variable dimulai dengan \n (Newline)
    export SERVICE_BLOCK="
  ${CONTAINER_NAME}:
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    env_file:
      - ./configs/.env.${CONTAINER_NAME}
    networks:
      - ${DEPLOY_ENV}_network
    ports:
      - \"${port}:${internal_port}\"
    volumes:
      - ./logs/${CONTAINER_NAME}:/app/logs"

    # Python Script: Safe YAML Insert
    python3 -c "
import os
import sys

file_path = '${DOCKER_COMPOSE_FILE}'
target_service = '  ${CONTAINER_NAME}:'
new_block = os.environ['SERVICE_BLOCK']

# Initial content if file doesn't exist
default_content = ['version: \"3.8\"\\n', 'services:\\n', 'networks:\\n', '  ${DEPLOY_ENV}_network:\\n', '    external: true\\n']

try:
    with open(file_path, 'r') as f:
        lines = f.readlines()
        if not lines: lines = default_content
except FileNotFoundError:
    lines = default_content

output_lines = []
skip = False
networks_index = -1

# 1. READ & CLEANUP OLD SERVICE
for i, line in enumerate(lines):
    if line.strip().startswith('networks:'):
        networks_index = len(output_lines)

    if line.startswith(target_service):
        skip = True
        continue
    
    if skip:
        stripped = line.strip()
        if not stripped: continue
        # Stop skip jika ketemu root key atau service lain
        if line[0] != ' ' and line[0] != '#': 
            skip = False
        elif line.startswith('  ') and not line.startswith('    '): 
            skip = False
        if skip: continue

    output_lines.append(line)

# 2. INSERT NEW SERVICE
# Logic: new_block sudah punya \n di awal (dari Bash).
# Kita hanya perlu menutup baris terakhir dengan satu \n.
if networks_index != -1:
    output_lines.insert(networks_index, new_block + '\\n') 
else:
    output_lines.append(new_block + '\\n')

# 3. WRITE BACK
with open(file_path, 'w') as f:
    f.writelines(output_lines)
"
}

# ==========================================
# Core Functions
# ==========================================

build_image() {
    log_info "Building Docker Image: ${IMAGE_NAME}"
    
    docker images --format '{{.Repository}}:{{.Tag}}' | grep "${PROJECT_NAME}" | xargs -r docker rmi -f 2>/dev/null || true
    
    docker build --no-cache \
        --build-arg ENV=${DEPLOY_ENV} \
        --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
        --build-arg VCS_REF=${CI_COMMIT_SHORT_SHA:-latest} \
        -t ${IMAGE_NAME} \
        -t ${PROJECT_NAME}:${DEPLOY_ENV}-latest \
        -t ${PROJECT_NAME}:latest .
}

deploy_app() {
    log_info "Starting Deployment for $CONTAINER_NAME"
    
    mkdir -p ${ENV_DIR}/logs/${CONTAINER_NAME}
    
    # 1. Siapkan File ENV
    if [ -f .env ]; then
        mv .env "${CONFIG_DIR}/.env.${CONTAINER_NAME}"
    else
        touch "${CONFIG_DIR}/.env.${CONTAINER_NAME}"
    fi
    
    # 2. Resolve Port & Internal Port (Generic)
    PORT=$(get_assigned_port)
    log_info "Resolved Host Port: $PORT"
    
    # Gunakan variable dari CI/CD jika ada, default ke 3140 (FE)
    INTERNAL_PORT="${INTERNAL_PORT:-3140}"
    log_info "Target Internal Port: $INTERNAL_PORT"
    
    # 3. Update Configuration Files
    update_cloudflare_config "${CONTAINER_NAME}" "${INTERNAL_PORT}"
    update_docker_compose "${PORT}" "${INTERNAL_PORT}"
    
    # 4. Register DNS (Tunnel ID from Env Var)
    log_info "Registering DNS..."
    docker run --rm \
        -v ${CLOUDFLARED_DIR}:/home/nonroot/.cloudflared \
        ${CLOUDFLARED_TUNNEL_IMAGE} \
        tunnel route dns -f ${TUNNEL_ID} ${FULL_HOSTNAME} > /dev/null 2>&1 || true

    # 5. Redeploy Container
    log_info "Recreating Container..."
    docker stop ${CONTAINER_NAME} 2>/dev/null || true
    docker rm ${CONTAINER_NAME} 2>/dev/null || true
    
    cd ${ENV_DIR}
    docker compose up -d ${CONTAINER_NAME}
    
    # 6. Restart Tunnel
    log_info "Restarting Tunnel Service..."
    docker compose restart ${TUNNEL_SERVICE_NAME}
    
    echo ""
    echo "🎉 Deployment Success!"
    echo "🌍 URL: https://${FULL_HOSTNAME}"
}

# ==========================================
# Main Execution
# ==========================================

case "${1}" in
    build) build_image ;;
    deploy) deploy_app ;;
    *) echo "Usage: $0 {build|deploy}"; exit 1 ;;
esac